export const constants = {
  tabs: "Tabs",
  explore: "Explore",
  myCourses: "My Courses",
  search: "Search",
  statistics: "Statistics",
  share: "Share",
  account: "Account",
  singleCourse: "Single Course",
  device: "Sandaru's Phone",
  password: "sandaru1234",
  ssid: "Piumi's Phone",
  ssidPass: "Piumi1234",
  contentHubTitle: "Piumi's Content Hub",
};
